
export const downloadCSVFromJson = (filename, arr, username) => {
  const array = [Object.keys(arr[0])].concat(arr);

  const csv = array
    .map((it) => {
      return Object.values(it).toString();
    })
    .join("\n");

const nameData = `Generated By: ${username}\n`;

  var link = document.createElement("a");
  link.setAttribute("href", "data:text/csv;charset=utf-8,%EF%BB%BF" + nameData + encodeURIComponent(csv));
  link.setAttribute("download", filename);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
